version: '3.8'

services:
  postgres:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: root
      POSTGRES_DB: STC
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "9080:9080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/STC
      SPRING_DATASOURCE_USERNAME: postgresql
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  postgres-data: